<?php
/**
 * SmsSchemaTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Ducksms
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Ducksms
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ducksms.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Ducksms;

use PHPUnit\Framework\TestCase;

/**
 * SmsSchemaTest Class Doc Comment
 *
 * @category    Class
 * @description SmsSchema
 * @package     Ducksms
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SmsSchemaTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SmsSchema"
     */
    public function testSmsSchema()
    {
    }

    /**
     * Test attribute "preview"
     */
    public function testPropertyPreview()
    {
    }

    /**
     * Test attribute "mobile_numbers"
     */
    public function testPropertyMobileNumbers()
    {
    }

    /**
     * Test attribute "message"
     */
    public function testPropertyMessage()
    {
    }

    /**
     * Test attribute "sender_id"
     */
    public function testPropertySenderId()
    {
    }

    /**
     * Test attribute "scheduled_at"
     */
    public function testPropertyScheduledAt()
    {
    }

    /**
     * Test attribute "callback_url"
     */
    public function testPropertyCallbackUrl()
    {
    }
}
