<?php
/**
 * SenderIDApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Ducksms
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Ducksms
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ducksms.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Ducksms;

use \Ducksms\Configuration;
use \Ducksms\ApiException;
use \Ducksms\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SenderIDApiTest Class Doc Comment
 *
 * @category Class
 * @package  Ducksms
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SenderIDApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createSender
     *
     * Create a Sender ID.
     *
     */
    public function testCreateSender()
    {
    }

    /**
     * Test case for deleteSender
     *
     * Delete a Sender ID.
     *
     */
    public function testDeleteSender()
    {
    }

    /**
     * Test case for getSender
     *
     * Get a single Sender ID.
     *
     */
    public function testGetSender()
    {
    }

    /**
     * Test case for listSender
     *
     * List Sender ID.
     *
     */
    public function testListSender()
    {
    }

    /**
     * Test case for updateSender
     *
     * Update a Sender ID.
     *
     */
    public function testUpdateSender()
    {
    }
}
